import { type NextPage } from "next";
import Head from "next/head";
import MainLayout from "@/components/layouts/MainLayout";
import ApplicationForm from "@/components/content/apply/ApplicationForm";

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Apply</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
          <h1 className="gradient-text mt-12 pr-28 text-3xl font-bold uppercase tracking-tighter">Apply</h1>
          <ApplicationForm />
      </MainLayout>
    </>
  );
};

export default Page;